### ISSUE TITLE
Clarify domain of index systemQueryOption

### ISSUE THREAD

**Issue by sthagen** [sthagen/odata-url-parser#55]
The spec states:

> 11.4.11 Positional Inserts
Collections of entity, complex, or primitive types annotated with the Core.PositionalInsert term (see [OData-VocCore]) support inserting items at a specific location via POST requests to the collection URL using the $index system query option. The value of the $index system query option is the zero-based ordinal position where the item is to be inserted. The ordinal positions of items within the collection greater than or equal to the inserted position are increased by one. A negative ordinal number indexes from the end of the collection, with -1 representing an insert as the last item in the collection.

Which reads as assigning the domain of the whole numbers (including negative ones') to index (despite the mention of zero-based ordinal position which just mentions the mapping required to apply the value to actual collection "positions").

The grammar (ABNF) keeps index expression value within non-negative numbers (extract after percent decoding).
```
index  = ( "$index" / "index" ) EQ 1*DIGIT

EQ     = "="
DIGIT  = %x30-39
```

**Comment by ralfhandl** [comment]
@sthagen Thanks for catching this, opened https://issues.oasis-open.org/browse/ODATA-1393 to track and repair it.

**Comment by ralfhandl** [comment]
@sthagen Please review https://github.com/oasis-tcs/odata-abnf/pull/27/files

**Comment by sthagen** [comment]
I switched to the [oasis-tcs/odata-abnf](https://github.com/oasis-tcs/odata-abnf/) variants of ABNF grammar and test cases (the test cases are not yet synchronized across formats)

**Comment by sthagen** [comment]
Propose to close this issue. Thank you @ralfhandl for the fast upstream handling of the issue.

**Comment by ralfhandl** [comment]
PR now uses `[ "-" ]`.
