### ISSUE TITLE
Derive from OData spec or define policy on repeated query options

### ISSUE THREAD

**Issue by sthagen** [sthagen/odata-url-parser#60]
Assuming we focus on libraries that match on a fixed dictionary of query option names the parsed values (this project delivers the tools for) we still have to make explicit if and how multiple such names (keys) are handled.

**Comment by ralfhandl** [comment]
For system query options the answer is in [5.1 System Query Options](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_SystemQueryOptions):

> The same system query option, irrespective of casing or whether or not it is prefixed with a $, MUST NOT be specified more than once for any resource.

I'd assume the same for custom query options until someone complains.

**Comment by sthagen** [comment]
Closing this issue, as the grammar cannot enforce this restriction without factorial explosion of alternatives and we focus on parsing the percent decoded expression values of single options (for a start).
