### ISSUE TITLE
Some ABNF productions contain optionals matching the empty string

### ISSUE THREAD

**Issue by sthagen** [sthagen/odata-url-parser#62]
When rewriting the ABNF grammar we encounter some optional components of productions that resolve to at least one alternative matching the empty string.

Example:
```abnf
; ...
collectionNavPath    = keyPredicate [ singleNavigation ]      ; <-- Example: singleNavigation matches empty string
                     / filterInPath [ collectionNavigation ]
                     / each [ boundOperation ]
                     / boundOperation
                     / count
                     / ref
                     / querySegment

keyPredicate     = simpleKey / compoundKey / keyPathSegments
; ...
singleNavigation = [ "/" optionallyQualifiedEntityTypeName ]  ; <-- optional 1/2
                   [ "/" propertyPath
                   / boundOperation
                   / ref 
                   / value  ; request the media resource of a media entity 
                   / querySegment
                   ]                                           ; <-- optional 2/2
; ...
```
In this case the solution could be to refactor the leading slash from the optional components into a leading mandatory component. Like so (not verfied yet):
```abnf
; ... 
singleNavigation = "/" ( [ optionallyQualifiedEntityTypeName ]
                       / ( [ optionallyQualifiedEntityTypeName "/" (
                           propertyPath
                         / boundOperation
                         / ref 
                         / value  ; request the media resource of a media entity 
                         / querySegment
                         ) ] )
                       )
; ...
```

Question to research: How can we avoid rules, where the production matches the empty string (in ABNF)

Maybe this is a bug of the ABNF schema? In that case we have no problems with an ANTLR grammar. Otherwise we have to research how to work around this rule triggering from no input at all.

Other candiates are within `boundOperation` and `propertyPath`.

**Comment by ralfhandl** [comment]
@sthagen That's a bug, someone else recently pointed me to it. Could you please open an issue in https://github.com/oasis-tcs/odata-abnf and list all places where you stumble over this?

**Comment by sthagen** [comment]
@ralfhandl - it seems the solution pattern of [oasis-tcs/odata-abnf#29](https://github.com/oasis-tcs/odata-abnf/pull/29) works. Thanks, that was fast. I completed the list in the issue [oasis-tcs/odata-abnf#28](https://github.com/oasis-tcs/odata-abnf/issues/28). Only the `complexColPath` may require additional thought (`complexPath` looks easy to be dealt with like the other two components).

**Comment by ralfhandl** [comment]
@sthagen Please check: have hopefully eliminated all potentially empty rules and applied the same pattern everywhere.
